name: Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
          # cache: 'poetry'  # doesn't work
      - name: Install poetry
        run: |
          python -m pip install poetry==1.8.3
      - name: Configure poetry
        run: |
          python -m poetry config virtualenvs.in-project true

      # for debugging
      - run: python --version
      - run: poetry debug info

      - name: Install dependencies
        run: |
          python -m poetry install
      # Can't figure out how to cache localstack's image
      - name: Bring up localstack and Lambda
        run: docker compose up ssmbak --detach
      - run: poetry run tests/test_localstack.sh -q --tb=line  # 18 passed in 24.90s
      - name: Pylint
        run: |
          poetry run pylint $(git ls-files '*.py')
      - run: poetry run pytype
