name: Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      # - name: Install and configure Poetry
      #   uses: snok/install-poetry@v1
      #   with:
      #     version: 1.8.3
      #     virtualenvs-create: true
      #     virtualenvs-in-project: true
      # - name: Load cached venv
      #   id: cached-poetry-dependencies
      #   uses: actions/cache@v3
      #   with:
      #     path: .venv
      #     key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}
      # - name: Install dependencies
      #   if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
      #   run: poetry install --no-interaction --no-root

      # # Can't figure out how to cache localstack's image
      # - name: Bring up localstack and Lambda
      #   run: docker compose up ssmbak --detach

      # - name: pytest
      #   run: poetry run tests/test_localstack.sh -q --tb=line  # 18 passed in 24.90s

      # - name: Pylint
      #   run: |
      #     poetry run pylint $(git ls-files '*.py')

      # - run: poetry run pytype
